# Site settings
course_name: "CS325: Designing for Accessibility"
course_semester: "Fall 2025"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wellesley-cs325.github.io/" # the base hostname & protocol for your site

schoolname: "Wellesley College"
schoolurl: "https://www.wellesley.edu/"
twitter_username: 

address: |
    Wellesley College
    106 Central Street
    Wellesley, MA 02481

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
